[package]
name = "mlmake"
version = "0.0.1"
edition = "2021"

[dependencies]
brush-core = "0.4"
brush-builtins = "0.1"
toml = "0.8"
serde = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
pty-process = "0.5"
libc = "0.2"
crossterm = "0.28"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 1
debug = true
